spring:
  application:
    name: javaweb
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
